name: Tmate Debug Session

on:
  workflow_dispatch:

jobs:
  tmate:
    name: Setup tmate session
    runs-on: ubuntu-latest
    steps:
    - name: Update System
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y git wget software-properties-common

    - name: Install tmate
      run: |
        sudo sh -c "echo 'deb http://repo.tmate.io ./' > /etc/apt/sources.list.d/tmate.list"
        wget -qO - http://repo.tmate.io/tmate.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install tmate -y

    - name: Run tmate
      run: tmate
