name: Tmate Debug Session

on:
  workflow_dispatch:

jobs:
  tmate:
    name: Setup tmate session
    runs-on: ubuntu-latest
    steps:
    - name: Update System
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y git wget software-properties-common

    - name: Install tmate
      run: |
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:tmate.io/archive
        sudo apt-get update
        sudo apt-get install -y tmate

    - name: Run tmate
      run: tmate
