name: Tmate Debug Session

on:
  workflow_dispatch:

jobs:
  tmate:
    name: Setup tmate session
    runs-on: ubuntu-latest
    steps:
    - name: Update System
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y git wget

    - name: Install tmate
      run: sudo apt-get install -y tmate

    - name: Run tmate
      run: tmate
