name: Debug workflow for boot image builder

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.16

