name: Build Kernel and Boot Image

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:buster-slim

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
            build-essential \
            fakeroot \
            libncurses5-dev \
            libssl-dev \
            ccache \
            bison \
            flex \
            libelf-dev \
            bc \
            wget \
            zip \
            p7zip-full \
            unzip

    - name: Setup toolchain
      run: |
        mkdir ~/toolchain
        wget -P ~/toolchain https://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/aarch64-linux-gnu/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz
        tar -xvf ~/toolchain/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz -C ~/toolchain
        rm ~/toolchain/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz
        echo "/root/toolchain/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu/bin" >> $GITHUB_PATH

    - name: Build Kernel
      run: |
        chmod +x ./build_kernel.sh
        ./build_kernel.sh

    - name: Download and extract magiskboot
      run: |
        wget -O magisk.zip https://github.com/topjohnwu/Magisk/releases/download/v26.1/Magisk-v26.1.apk
        unzip magisk.zip lib/x86_64/libmagiskboot.so -d magisk
        mv magisk/lib/x86_64/libmagiskboot.so /usr/bin/magiskboot
        chmod +x /usr/bin/magiskboot

    - name: Download and extract stock boot image
      run: |
        mkdir repack
        cd repack
        wget https://raw.githubusercontent.com/DeadPool-4422/a7y18lte-Resources/main/stock-boot.7z
        7z x stock-boot.7z
        rm stock-boot.7z

    - name: Unpack, replace kernel, and repack boot image
      run: |
        cd repack
        magiskboot unpack boot.img
        mv boot.img ../
        rm kernel
        cp ../arch/arm64/boot/Image ./kernel
        magiskboot repack ../boot.img boot.img

    - name: Zip boot folder
      run: |
        zip -r boot.zip ./arch/arm64/boot/

    - name: Upload boot image
      uses: actions/upload-artifact@v2
      with:
        name: boot-image
        path: repack/boot.img

    - name: Upload boot folder
      uses: actions/upload-artifact@v2
      with:
        name: boot-folder
        path: boot.zip
