name: Debug Workflow

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable tmate debugging'
        required: false
        default: false

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up tmate session
        uses: mxschmitt/action-tmate@v3
        if: github.event.inputs.debug_enabled == 'true'
        
      - name: Your normal steps
        run: echo "Place your commands here"

